
GET http://localhost:8081/pengurus
###
GET http://localhost:8081/admin
###
GET http://localhost:8081/admin/getadmin/1
###
PUT  http://localhost:8081/admin/updateadmin/7
Content-Type: application/json

{
    "name": "Dwi",
    "nim": "223200230",
    "email": "Diklat@afdh",
    "role": "Admin"
}
###

GET http://localhost:8081/pengurus/editpengurus/1
###

DELETE  http://localhost:8081/pengurus/deletepengurus/9
###
DELETE  http://localhost:8081/admin/deleteadmin/2
###

POST   http://localhost:8081/pengurus/tambahpengurus
Content-Type: application/json

{
    "nama": "Dwi Prasetia",
    "nama_panggilan": "Dwi Prasetia",
    "nim": "223200230",
    "divisi": "Diklat",
    "posisi": "Staff",
    "foto": "",
    "ig_link": "asdf",
    "linkedin_link": "asfdas",
    "github_link": "af"
}

###
POST  http://localhost:8081/admin/tambahadmin
Content-Type: application/json

{
    "name": "Dwi",
    "nim": "223200230",
    "email": "Diklat@afdh",
    "role": "Admin",
    "password": "asfdsdfgaa"
}
###
